/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StandsRouteImport } from './routes/stands'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as ChannelSlugRouteImport } from './routes/channel.$slug'
import { Route as JobIdRouteImport } from './routes/job.$id'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as MenuLoginRouteImport } from './routes/menu.login'
import { Route as MenuNotificationsRouteImport } from './routes/menu.notifications'
import { Route as MenuPrivacyRouteImport } from './routes/menu.privacy'
import { Route as MenuProfileRouteImport } from './routes/menu.profile'
import { Route as MenuSavedRouteImport } from './routes/menu.saved'
import { Route as MenuSettingsRouteImport } from './routes/menu.settings'
import { Route as MenuSourcesRouteImport } from './routes/menu.sources'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as StandsIndexRouteImport } from './routes/stands.index'
import { Route as StandsShowcaseRouteImport } from './routes/stands.showcase'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StandsRoute = StandsRouteImport.update({
  id: '/stands',
  path: '/stands',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelSlugRoute = ChannelSlugRouteImport.update({
  id: '/channel/$slug',
  path: '/channel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobIdRoute = JobIdRouteImport.update({
  id: '/job/$id',
  path: '/job/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuLoginRoute = MenuLoginRouteImport.update({
  id: '/menu/login',
  path: '/menu/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuNotificationsRoute = MenuNotificationsRouteImport.update({
  id: '/menu/notifications',
  path: '/menu/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuPrivacyRoute = MenuPrivacyRouteImport.update({
  id: '/menu/privacy',
  path: '/menu/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuProfileRoute = MenuProfileRouteImport.update({
  id: '/menu/profile',
  path: '/menu/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSavedRoute = MenuSavedRouteImport.update({
  id: '/menu/saved',
  path: '/menu/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSettingsRoute = MenuSettingsRouteImport.update({
  id: '/menu/settings',
  path: '/menu/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSourcesRoute = MenuSourcesRouteImport.update({
  id: '/menu/sources',
  path: '/menu/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StandsIndexRoute = StandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StandsRoute,
} as any)
const StandsShowcaseRoute = StandsShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => StandsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stands': typeof StandsRouteWithChildren
  '/updates': typeof UpdatesRoute
  '/channel/$slug': typeof ChannelSlugRoute
  '/job/$id': typeof JobIdRoute
  '/menu/login': typeof MenuLoginRoute
  '/menu/notifications': typeof MenuNotificationsRoute
  '/menu/privacy': typeof MenuPrivacyRoute
  '/menu/profile': typeof MenuProfileRoute
  '/menu/saved': typeof MenuSavedRoute
  '/menu/settings': typeof MenuSettingsRoute
  '/menu/sources': typeof MenuSourcesRoute
  '/post/$id': typeof PostIdRoute
  '/stands/showcase': typeof StandsShowcaseRoute
  '/menu/': typeof MenuIndexRoute
  '/stands/': typeof StandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/updates': typeof UpdatesRoute
  '/channel/$slug': typeof ChannelSlugRoute
  '/job/$id': typeof JobIdRoute
  '/menu/login': typeof MenuLoginRoute
  '/menu/notifications': typeof MenuNotificationsRoute
  '/menu/privacy': typeof MenuPrivacyRoute
  '/menu/profile': typeof MenuProfileRoute
  '/menu/saved': typeof MenuSavedRoute
  '/menu/settings': typeof MenuSettingsRoute
  '/menu/sources': typeof MenuSourcesRoute
  '/post/$id': typeof PostIdRoute
  '/stands/showcase': typeof StandsShowcaseRoute
  '/menu': typeof MenuIndexRoute
  '/stands': typeof StandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stands': typeof StandsRouteWithChildren
  '/updates': typeof UpdatesRoute
  '/channel/$slug': typeof ChannelSlugRoute
  '/job/$id': typeof JobIdRoute
  '/menu/login': typeof MenuLoginRoute
  '/menu/notifications': typeof MenuNotificationsRoute
  '/menu/privacy': typeof MenuPrivacyRoute
  '/menu/profile': typeof MenuProfileRoute
  '/menu/saved': typeof MenuSavedRoute
  '/menu/settings': typeof MenuSettingsRoute
  '/menu/sources': typeof MenuSourcesRoute
  '/post/$id': typeof PostIdRoute
  '/stands/showcase': typeof StandsShowcaseRoute
  '/menu/': typeof MenuIndexRoute
  '/stands/': typeof StandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/notifications'
    | '/search'
    | '/sitemap.xml'
    | '/stands'
    | '/updates'
    | '/channel/$slug'
    | '/job/$id'
    | '/menu/login'
    | '/menu/notifications'
    | '/menu/privacy'
    | '/menu/profile'
    | '/menu/saved'
    | '/menu/settings'
    | '/menu/sources'
    | '/post/$id'
    | '/stands/showcase'
    | '/menu/'
    | '/stands/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/notifications'
    | '/search'
    | '/sitemap.xml'
    | '/updates'
    | '/channel/$slug'
    | '/job/$id'
    | '/menu/login'
    | '/menu/notifications'
    | '/menu/privacy'
    | '/menu/profile'
    | '/menu/saved'
    | '/menu/settings'
    | '/menu/sources'
    | '/post/$id'
    | '/stands/showcase'
    | '/menu'
    | '/stands'
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/notifications'
    | '/search'
    | '/sitemap.xml'
    | '/stands'
    | '/updates'
    | '/channel/$slug'
    | '/job/$id'
    | '/menu/login'
    | '/menu/notifications'
    | '/menu/privacy'
    | '/menu/profile'
    | '/menu/saved'
    | '/menu/settings'
    | '/menu/sources'
    | '/post/$id'
    | '/stands/showcase'
    | '/menu/'
    | '/stands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRoute
  NotificationsRoute: typeof NotificationsRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StandsRoute: typeof StandsRouteWithChildren
  UpdatesRoute: typeof UpdatesRoute
  ChannelSlugRoute: typeof ChannelSlugRoute
  JobIdRoute: typeof JobIdRoute
  MenuLoginRoute: typeof MenuLoginRoute
  MenuNotificationsRoute: typeof MenuNotificationsRoute
  MenuPrivacyRoute: typeof MenuPrivacyRoute
  MenuProfileRoute: typeof MenuProfileRoute
  MenuSavedRoute: typeof MenuSavedRoute
  MenuSettingsRoute: typeof MenuSettingsRoute
  MenuSourcesRoute: typeof MenuSourcesRoute
  PostIdRoute: typeof PostIdRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stands': {
      id: '/stands'
      path: '/stands'
      fullPath: '/stands'
      preLoaderRoute: typeof StandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$slug': {
      id: '/channel/$slug'
      path: '/channel/$slug'
      fullPath: '/channel/$slug'
      preLoaderRoute: typeof ChannelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$id': {
      id: '/job/$id'
      path: '/job/$id'
      fullPath: '/job/$id'
      preLoaderRoute: typeof JobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/login': {
      id: '/menu/login'
      path: '/menu/login'
      fullPath: '/menu/login'
      preLoaderRoute: typeof MenuLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/notifications': {
      id: '/menu/notifications'
      path: '/menu/notifications'
      fullPath: '/menu/notifications'
      preLoaderRoute: typeof MenuNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/privacy': {
      id: '/menu/privacy'
      path: '/menu/privacy'
      fullPath: '/menu/privacy'
      preLoaderRoute: typeof MenuPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/profile': {
      id: '/menu/profile'
      path: '/menu/profile'
      fullPath: '/menu/profile'
      preLoaderRoute: typeof MenuProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/saved': {
      id: '/menu/saved'
      path: '/menu/saved'
      fullPath: '/menu/saved'
      preLoaderRoute: typeof MenuSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/settings': {
      id: '/menu/settings'
      path: '/menu/settings'
      fullPath: '/menu/settings'
      preLoaderRoute: typeof MenuSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/sources': {
      id: '/menu/sources'
      path: '/menu/sources'
      fullPath: '/menu/sources'
      preLoaderRoute: typeof MenuSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stands/': {
      id: '/stands/'
      path: '/'
      fullPath: '/stands/'
      preLoaderRoute: typeof StandsIndexRouteImport
      parentRoute: typeof StandsRoute
    }
    '/stands/showcase': {
      id: '/stands/showcase'
      path: '/showcase'
      fullPath: '/stands/showcase'
      preLoaderRoute: typeof StandsShowcaseRouteImport
      parentRoute: typeof StandsRoute
    }
  }
}

interface StandsRouteChildren {
  StandsShowcaseRoute: typeof StandsShowcaseRoute
  StandsIndexRoute: typeof StandsIndexRoute
}

const StandsRouteChildren: StandsRouteChildren = {
  StandsShowcaseRoute: StandsShowcaseRoute,
  StandsIndexRoute: StandsIndexRoute,
}

const StandsRouteWithChildren =
  StandsRoute._addFileChildren(StandsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  NotificationsRoute: NotificationsRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StandsRoute: StandsRouteWithChildren,
  UpdatesRoute: UpdatesRoute,
  ChannelSlugRoute: ChannelSlugRoute,
  JobIdRoute: JobIdRoute,
  MenuLoginRoute: MenuLoginRoute,
  MenuNotificationsRoute: MenuNotificationsRoute,
  MenuPrivacyRoute: MenuPrivacyRoute,
  MenuProfileRoute: MenuProfileRoute,
  MenuSavedRoute: MenuSavedRoute,
  MenuSettingsRoute: MenuSettingsRoute,
  MenuSourcesRoute: MenuSourcesRoute,
  PostIdRoute: PostIdRoute,
  MenuIndexRoute: MenuIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
